name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # If the pkg server flakes, set this to "" to bypass it and fetch via git:
      # JULIA_PKG_SERVER: ""
      JULIA_NUM_THREADS: 2
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'   # or '1' to track latest stable

      - uses: julia-actions/cache@v1

      # (Optional) Print registries to help debug missing/old registries
      - name: Show registries
        run: julia --color=yes -e 'using Pkg; Pkg.Registry.status()'

      # Ensure General is present & up-to-date, then resolve/instantiate/precompile
      - name: Instantiate project
        run: |
          julia --project=. --color=yes -e '
            using Pkg
            try
              Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/JuliaRegistries/General.git"))
            catch e
              @info "Registry add skipped (likely already present)" exception=e
            end
            Pkg.Registry.update()
            Pkg.resolve(); Pkg.instantiate(); Pkg.precompile()
          '

      # Run your tests
      - name: Run tests
        run: julia --project=. --color=yes -e 'using Pkg; Pkg.test(; coverage=true)'
