name: TagBot
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
